### PR TITLE
nix

### PR DESCRIPTION
**Pull request by PoolloverNathan**

### CODE REVIEW

**Comment by BeanGalSolina** [comment]
@PoolloverNathan my PR adds some stuff that you will need to account for so for now not approving

**Review by BeanGalSolina — CHANGES_REQUESTED** [review]
1. What is u want to add it as a package in my config
2. Default configuration
3. Set config location to `$HOME/.config/fig manager/config.properties`

**Review by BeanGalSolina — CHANGES_REQUESTED** [review]
Don't rely on fia. if you want per-system use flake-utils

**Comment by PoolloverNathan** [comment]
> Don't rely on fia. if you want per-system use flake-utils

will change, gmas to restart services

**Comment by BeanGalSolina** [comment]
@PoolloverNathan did you test this?

**Comment by PoolloverNathan** [comment]
> @PoolloverNathan did you test this?

no

**Review by BeanGalSolina — APPROVED** [review]
Supposedly it works

**Pull request merged**
